name: Security

on:
  push:
  pull_request:

jobs:

  security:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
         php-version: ${{ matrix.php }}
         extensions: gd, intl, json

      - uses: actions/cache@v1
        id: cache-composer
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.php }}-

      - run: mkdir -p /home/runner/{.composer/cache,.config/composer}
        if: steps.cache-composer.outputs.cache-hit != 'true'

      - name: Composer v2
        run: sudo composer self-update --2

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ github.token }}

      - uses: actions/checkout@v2
        
      - name: Setup some requirements
        run: |
          composer config --no-plugins allow-plugins true
          composer config extra.symfony.allow-contrib true
          composer config secure-http false
          composer config --unset platform.php
              
      - name: Install PHP dependencies
        run: composer install

      - uses: symfonycorp/security-checker-action@v4
